### ISSUE TITLE
UIKit framework 에서 SwiftUI Preview 사용하기

### ISSUE THREAD

**Issue by HoJongPARK** [DeveloperAcademy-POSTECH/MC3-Team-18-Momin#7]
## 사용 방법

- ViewController 를 Preview 로 변환하려는 경우 ViewController 파일 하단에 아래 코드를 첨부하면 됩니다.
```swift
#if DEBUG
import SwiftUI
struct PreviewName: PreviewProvider {
    static var previews: some View {
        TestViewController().toPreview()
    }
}
#endif
```
- 만약 Storyboard 에서 ViewController 를 가져온다면, UIStoryboard(name: "Main", bundle: nil).instantiateViewController("TestUIViewController").toPreview() 와 같이 작성해서 사용하시면 됩니다.

- View 를 Preview 변환하려는 경우 UIView 파일 하단에 아래 코드를 첨부하면 됩니다.
```swift
#if DEBUG
import SwiftUI
struct PreviewName: PreviewProvider {
    static var previews: some View {
        TestUIView().toPreview()
    }
}
#endif
```

## References

[블로그](https://taekki-dev.tistory.com/21)

**Comment by Minkyeong-Ko** [comment]
<img width="294" alt="스크린샷 2022-07-19 오후 7 50 28(2)" src="https://user-images.githubusercontent.com/78426896/179733401-8d4acb0b-829b-49d5-9167-f72c07c1850d.png">

Preview가 이 버전의 macOS에서는 사용할 수가 없다고 오류가 뜨는데 혹시 다른분들도 그러신가요..?!

**Comment by HoJongPARK** [comment]
> 감사합니다 호종이!
> 
> <img alt="스크린샷 2022-07-19 오후 7 50 28(2)" width="294" src="https://user-images.githubusercontent.com/78426896/179733401-8d4acb0b-829b-49d5-9167-f72c07c1850d.png">
> 
> 근데 저는 Preview가 이 버전의 macOS에서는 사용할 수가 없다고 오류가 뜨는데 혹시 다른분들도 그러신가요..?!

그게 실제로 버전때문에 그런게 아니고, 프리뷰를 빌드하는동안 코드 상에서 에러가 뜨면 그렇게 되는 것으로 알고 있어요

**Comment by Minkyeong-Ko** [comment]
앗 정말 코드상에서 제 실수로 오류가 있었네요ㅠㅠ 지금은 잘 동작합니다 감사해요!
